<template>
    <div id="app">
        <templateInvoiceCar ref="childInvoiceCar" :invoiceData="formData" />

    </div>
</template>

<script>


export default {
    name: 'App',
    data() {
        return {
            formData: {
                "id": "28ca102d91e3cd0b1de9eab8b1b8ca76",
                "orderNum": "shhy20240812000030",
                "settlementNo": null,
                "fpqqlsh": "00080180-186a-49f1-84d6-6d2aad98e7fa",
                "itype": "87",
                "invoiceType": "87",
                "invoiceStatus": "10",
                "dataResources": null,
                "kplx": "0",
                "zsfs": "0",
                "xsfNsrsbh": "913***********",
                "xsfMc": "上海****汽车销售服务有限公司",
                "xsfDzdh": "上海市杨浦区国和路****号*幢****室 13*******86",
                "xsfDz": "上海市杨浦区国和路****号*幢****室",
                "xsfYhzh": "448*******",
                "xsfYhmc": "中国银行股份有限公司上海市*********支行",
                "gmfNsrsbh": "3101**************",
                "gmfMc": "王晔",
                "gmfDz": null,
                "gmfDzdh": " ",
                "gmfYhmc": null,
                "gmfYhzh": null,
                "fpHm": "24312000000*********",
                "fpDm": "13100********",
                "jym": null,
                "kprq": "20240812",
                "jqbh": null,
                "fpMw": null,
                "kpr": "陈***",
                "skr": "",
                "fhr": "",
                "yfpDm": "",
                "yfpHm": "",
                "jshj": 236000,
                "hjje": 208849.56,
                "hjse": 27150.44,
                "kce": 0,
                "bz": "一车一票",
                "pdfKey": null,
                "pdfUrl": "0",
                "pdfItemKey": null,
                "pdfItemUrl": "0",
                "jffPhone": "1381*******",
                "jffEmail": null,
                "pdfKeyRemoting": null,
                "pdfItemKeyRemoting": null,
                "tspz": "00",
                "pdfCreateTime": null,
                "kpzdbs": null,
                "ewm": "01,33,131002320651,00788325,208849.56,20240812,916968,F620,",
                "sslkjly": null,
                "yfplx": null,
                "ykprq": null,
                "chyydm": null,
                "xsfDh": "1390*******",
                "xsfKhh": "中国银行股份有限公司上海市********支行",
                "gmfDh": null,
                "gmfKhh": null,
                "tdyslxdm": "00",
                "hsbz": null,
                "jbrxm": null,
                "jbrzjhm": null,
                "jbrzjzldm": null,
                "jbrnsrsbh": null,
                "jbrgj": null,
                "zdhqbsdz": null,
                "userId": null,
                "userName": null,
                "loginName": null,
                "gfxxconfirm": null,
                "zrrbs": null,
                "ewmUrl": null,
                "qdPdfUrl": null,
                "qdOfdUrl": null,
                "qdXmlUrl": null,
                "hzfpxxqrdid": null,
                "hzfpxxqrdNo": "",
                "taxNoType": null,
                "yfplxdm": null,
                "ytdyslxdm": null,
                "status": "2",
                "redInvoiceStatus": null,
                "returnmsg": null,
                "ncpsgzjlx": null,
                "created": "2024-08-12",
                "providerCode": null,
                "companyId": "501803b992b0e6ead0cb220cca43d563",
                "invoiceItemList": [
                    {
                        "id": "521c1e6f51763af8f6578969996adf82",
                        "companyId": "501803b992b0e6ead0cb220cca43d563",
                        "idx": "28ca102d91e3cd0b1de9eab8b1b8ca76",
                        "orderNum": null,
                        "fpqqlsh": null,
                        "kprq": "2024-08-12",
                        "fphhh": 1,
                        "fphxz": "0",
                        "spb": null,
                        "zxbm": null,
                        "yhzcbs": "0",
                        "lslbs": "",
                        "zzstsgl": "",
                        "xmmc": "*机动车*轿车",
                        "ggxh": "LBV54FF02RM890539",
                        "dw": "",
                        "xmdjOld": 208849.557522,
                        "xmje": 208849.56,
                        "sl": "0.13",
                        "se": 27150.44,
                        "xmsl": 1,
                        "xmdj": 208849.55752212388,
                        "kce": 0,
                        "ssflbm": "1090305010300000000",
                        "tdzsfsdm": null,
                        "zzstsgldm": null,
                        "xmjc": "机动车",
                        "zkje": null,
                        "xmhsje": 236000,
                        "yhzc": null,
                        "commodityName": "轿车"
                    }
                ],
                "elementCode": "00",
                "cpxh": "宝马牌/BMW7200JM",
                "cd": "沈阳市",
                "hgzh": "WBG380005903468",
                "jkzmsh": "无",
                "sjdh": "无",
                "fdjhm": "8713C227",
                "cjh": "LBV************",
                "cldw": "",
                "xcrs": "5",
                "wspzhm": "",
                "cllxDm": "轿车",
                "scqymc": "*****汽车有限公司",
                "jdctzclsbdhuuid": "1715257781902561664",
                "pl": null,
                "zpFppzDm": "000008102600",
                "zzfpdm": "131002320651",
                "zzfphm": "00788325",
                "swjgmc": "国家税务总局上海市杨浦区税务局第二税务所",
                "swjgdm": "13101102200",
                "zjmc": null,
                "zflx": null
            }
        }
    },
    mounted() {
        console.log('1212121');
    }
}
</script>

<style lang="scss"></style>